// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tatawwa3.Infrastructure.Data;

#nullable disable

namespace Tatawwa3.Infrastructure.Migrations
{
    [DbContext(typeof(Tatawwa3DbContext))]
    [Migration("20250715065816_addedOpportunityIdtoTeam")]
    partial class addedOpportunityIdtoTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Achievement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasRequiredSkills")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MotivationLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = "app-1",
                            ApplicationDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4613),
                            HasRequiredSkills = true,
                            IsDeleted = false,
                            MotivationLetter = "I am passionate about helping children learn.",
                            Note = "Looking forward to this opportunity.",
                            OpportunityID = "opp-1",
                            Status = 0,
                            VolunteerID = "vol-user-1"
                        },
                        new
                        {
                            Id = "app-2",
                            ApplicationDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttachmentPath = "attachments/volunteer_cv.pdf",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4616),
                            HasRequiredSkills = true,
                            IsDeleted = false,
                            MotivationLetter = "I have prior experience in similar events.",
                            Note = "Excited to participate.",
                            OpportunityID = "opp-2",
                            Status = 1,
                            VolunteerID = "vol-user-1"
                        },
                        new
                        {
                            Id = "app-3",
                            ApplicationDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttachmentPath = "attachments/volunteer_cv.pdf",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4618),
                            HasRequiredSkills = true,
                            IsDeleted = false,
                            MotivationLetter = "I have prior experience in similar events.",
                            Note = "Excited to participate.",
                            OpportunityID = "opp-1",
                            Status = 0,
                            VolunteerID = "vol_prof2"
                        },
                        new
                        {
                            Id = "app-4",
                            ApplicationDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AttachmentPath = "attachments/volunteer_cv.pdf",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4621),
                            HasRequiredSkills = true,
                            IsDeleted = false,
                            MotivationLetter = "I have prior experience in similar events.",
                            Note = "Excited to participate.",
                            OpportunityID = "opp-4",
                            Status = 0,
                            VolunteerID = "vol_prof2"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "org-user-1",
                            AccessFailedCount = 0,
                            City = "Cairo",
                            ConcurrencyStamp = "822243dd-5b07-434e-b0bb-47170187fc81",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4176),
                            Email = "org@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NationalID = "12345678901234",
                            NormalizedEmail = "ORG@EXAMPLE.COM",
                            NormalizedUserName = "ORG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6fBKgYj6nRAiD3F6jHUWfXeCmgVi+e3kq9a+vZ7O9GsG2vEMiRKzLskroIfvHHng==",
                            PhoneNumber = "01000000000",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "ec32e818-717a-4506-b01e-8200d44a367b",
                            TwoFactorEnabled = false,
                            UserName = "org@example.com"
                        },
                        new
                        {
                            Id = "vol-user-1",
                            AccessFailedCount = 0,
                            City = "Assiut",
                            ConcurrencyStamp = "627040fa-8519-4d49-978b-11adc0a5cfdb",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4306),
                            Email = "volunteer@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NationalID = "98765432109876",
                            NormalizedEmail = "VOLUNTEER@EXAMPLE.COM",
                            NormalizedUserName = "VOLUNTEER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6fBKgYj6nRAiD3F6jHUWfXeCmgVi+e3kq9a+vZ7O9GsG2vEMiRKzLskroIfvHHng==",
                            PhoneNumber = "01111111111",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "3bb58de2-bb62-4319-b739-579c341083f1",
                            TwoFactorEnabled = false,
                            UserName = "volunteer@example.com"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Attendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("HoursWorked")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ParticipationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParticipationID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4417),
                            Description = "Educational programs and initiatives",
                            Icon = "education.png",
                            IsDeleted = false,
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParticipationID")
                        .IsUnique();

                    b.HasIndex("VolunteerID");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = "cert-1",
                            CertificateNumber = "CERT-2025-001",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4792),
                            IsDeleted = false,
                            IsVerified = true,
                            IssueDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Seeded Org",
                            ParticipationID = "participation-1",
                            Title = "Coding for Kids Participation",
                            TotalHours = 12.5f,
                            VerificationCode = "VERIF123",
                            VolunteerID = "vol-user-1"
                        },
                        new
                        {
                            Id = "cert-2",
                            CertificateNumber = "CERT-2025-001",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4796),
                            IsDeleted = false,
                            IsVerified = true,
                            IssueDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Seeded Org",
                            ParticipationID = "participation-3",
                            Title = "Coding for Kids Participation",
                            TotalHours = 12.5f,
                            VerificationCode = "VERIF123",
                            VolunteerID = "vol_prof2"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasPreviousExperience")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.MailSetting.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwordResetTokens");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvitationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnApplicationAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnCertificateIssued")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnNewVolunteerApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnOpportunityCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnOpportunityRecommendations")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnVolunteerApplicationUnderReview")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notificationPreferences");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeactivationRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("OrganizationProfiles");

                    b.HasData(
                        new
                        {
                            Id = "org-profile-1",
                            City = "minya",
                            CommercialRegistration = "REG123456",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4254),
                            IsDeactivationRequested = false,
                            IsDeleted = false,
                            IsVerified = true,
                            OrganizationName = "Seeded Org",
                            OrganizationType = 0,
                            Status = 0,
                            UserID = "org-user-1"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalAttendedHours")
                        .HasColumnType("real");

                    b.Property<string>("VolunteerID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("VolunteerID");

                    b.ToTable("Participations");

                    b.HasData(
                        new
                        {
                            Id = "participation-1",
                            ApplicationID = "app-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4737),
                            FirstCheckIn = new DateTime(2025, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastCheckOut = new DateTime(2025, 6, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OpportunityId = "opp-1",
                            Status = 1,
                            TotalAttendedHours = 12.5f,
                            VolunteerID = "vol-user-1"
                        },
                        new
                        {
                            Id = "participation-2",
                            ApplicationID = "app-2",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4740),
                            FirstCheckIn = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastCheckOut = new DateTime(2025, 6, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OpportunityId = "opp-2",
                            Status = 1,
                            TotalAttendedHours = 8f,
                            VolunteerID = "vol-user-1"
                        },
                        new
                        {
                            Id = "participation-3",
                            ApplicationID = "app-3",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4743),
                            FirstCheckIn = new DateTime(2025, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastCheckOut = new DateTime(2025, 6, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OpportunityId = "opp-1",
                            Status = 1,
                            TotalAttendedHours = 12.5f,
                            VolunteerID = "vol_prof2"
                        },
                        new
                        {
                            Id = "participation-4",
                            ApplicationID = "app-4",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4746),
                            FirstCheckIn = new DateTime(2025, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastCheckOut = new DateTime(2025, 6, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OpportunityId = "opp-4",
                            Status = 1,
                            TotalAttendedHours = 12.5f,
                            VolunteerID = "vol_prof2"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skilless", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityID");

                    b.ToTable("skillesses");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skills", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLinkedToOpportunity")
                        .HasColumnType("bit");

                    b.Property<int?>("JoinPermission")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamGoals")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = "team-001",
                            CategoryId = "cat-edu-1",
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4462),
                            CreationDate = new DateTime(2025, 6, 30, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4453),
                            Description = "Team responsible for organizing educational initiatives.",
                            InternalNotes = "Priority team for large campaigns",
                            IsDeleted = false,
                            IsLinkedToOpportunity = true,
                            JoinPermission = 0,
                            MaxMembers = 20,
                            Name = "Education Support Team",
                            OrganizationID = "org-profile-1",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.TeamMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeamID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = "member-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4501),
                            IsDeleted = false,
                            JoinDate = new DateTime(2025, 7, 10, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4499),
                            Role = "Leader",
                            TeamID = "team-1",
                            VolunteerID = "vol-user-1"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerAchievement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AchievementID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VolunteerID");

                    b.ToTable("VolunteerAchievements");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerInvitation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("InvitationType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonalMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerInvitations");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenderRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAttendanceTracked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCertificateAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("TeamId");

                    b.ToTable("VolunteerOpportunities");

                    b.HasData(
                        new
                        {
                            Id = "opp-1",
                            CategoryID = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4541),
                            Description = "Help young children learn basic English skills.",
                            EndDate = new DateTime(2025, 8, 24, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4539),
                            Image = "english-teaching.png",
                            IsDeleted = false,
                            Location = "Cairo",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 10,
                            StartDate = new DateTime(2025, 7, 25, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4538),
                            Status = 1,
                            Title = "Teaching Kids English"
                        },
                        new
                        {
                            Id = "opp-2",
                            CategoryID = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4548),
                            Description = "Lead a reading club for teenagers.",
                            EndDate = new DateTime(2025, 8, 9, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4546),
                            Image = "reading-club.png",
                            IsDeleted = false,
                            Location = "Assiut",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 5,
                            StartDate = new DateTime(2025, 7, 20, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4546),
                            Status = 1,
                            Title = "Reading Club Facilitator"
                        },
                        new
                        {
                            Id = "opp-3",
                            CategoryID = "cat-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4551),
                            Description = "Teach basic coding to children in underserved communities.",
                            EndDate = new DateTime(2025, 8, 4, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4550),
                            Image = "coding-kids.png",
                            IsDeleted = false,
                            Location = "Jeddah",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 15,
                            StartDate = new DateTime(2025, 7, 25, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4550),
                            Status = 1,
                            TeamId = "team-1",
                            Title = "Coding for Kids"
                        },
                        new
                        {
                            Id = "opp-4",
                            CategoryID = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4555),
                            Description = "Teach basic coding to adults in underserved communities.",
                            EndDate = new DateTime(2025, 8, 4, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4554),
                            Image = "coding-kids.png",
                            IsDeleted = false,
                            Location = "Assiut",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 15,
                            StartDate = new DateTime(2025, 7, 25, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4554),
                            Status = 1,
                            TeamId = "cf0cf8e1-5a62-4315-9c90-3f8b727b8251",
                            Title = "programing"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("VolunteerProfiles");

                    b.HasData(
                        new
                        {
                            Id = "vol-user-1",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4352),
                            Interests = "[\"Education\",\"Health\"]",
                            IsDeleted = false,
                            IsVerified = false,
                            Rating = 0f,
                            Status = 0,
                            TotalHours = 0f,
                            UserID = "vol-user-1"
                        },
                        new
                        {
                            Id = "vol_prof2",
                            CreatedAt = new DateTime(2025, 7, 15, 6, 58, 13, 812, DateTimeKind.Utc).AddTicks(4386),
                            Interests = "[\"Education\",\"Health\"]",
                            IsDeleted = false,
                            IsVerified = false,
                            Rating = 0f,
                            Status = 0,
                            TotalHours = 0f,
                            UserID = "1b5b5731-bcf1-4178-87ad-cf43dac0bbeb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Participation", "Participation")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Participation", "Participation")
                        .WithOne("Certificate")
                        .HasForeignKey("Tatawwa3.Domain.Entities.Certificate", "ParticipationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany("Certificates")
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Participation");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.MailSetting.PasswordResetToken", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("Tatawwa3.Domain.Entities.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithOne("OrganizationProfile")
                        .HasForeignKey("Tatawwa3.Domain.Entities.OrganizationProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Application", "Application")
                        .WithOne("Participation")
                        .HasForeignKey("Tatawwa3.Domain.Entities.Participation", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany("Participations")
                        .HasForeignKey("VolunteerID");

                    b.Navigation("Application");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Review", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany("Reviews")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skilless", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skills", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.OrganizationProfile", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerAchievement", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerInvitation", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Category", "Category")
                        .WithMany("Opportunities")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.OrganizationProfile", "Organization")
                        .WithMany("VolunteerOpportunities")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany("Opportunities")
                        .HasForeignKey("TeamId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerProfile", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Category", "Category")
                        .WithMany("VolunteerProfiles")
                        .HasForeignKey("CategoryId1");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("Tatawwa3.Domain.Entities.VolunteerProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("NotificationPreference");

                    b.Navigation("OrganizationProfile");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.Navigation("Opportunities");

                    b.Navigation("VolunteerProfiles");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("VolunteerOpportunities");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("RequiredSkills");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerProfile", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
