// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tatawwa3.Infrastructure.Data;

#nullable disable

namespace Tatawwa3.Infrastructure.Migrations
{
    [DbContext(typeof(Tatawwa3DbContext))]
    [Migration("20250627114105_AddVolunteerInvitationTablee")]
    partial class AddVolunteerInvitationTablee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Achievement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasRequiredSkills")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MotivationLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "org-user-1",
                            AccessFailedCount = 0,
                            City = "Cairo",
                            ConcurrencyStamp = "4c54c0ec-d64e-41db-9594-f21200d3afbd",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3651),
                            Email = "org@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NationalID = "12345678901234",
                            NormalizedEmail = "ORG@EXAMPLE.COM",
                            NormalizedUserName = "ORG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6fBKgYj6nRAiD3F6jHUWfXeCmgVi+e3kq9a+vZ7O9GsG2vEMiRKzLskroIfvHHng==",
                            PhoneNumber = "01000000000",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "96008ce4-f1ca-48ef-8679-052d37860e77",
                            TwoFactorEnabled = false,
                            UserName = "org@example.com"
                        },
                        new
                        {
                            Id = "vol-user-1",
                            AccessFailedCount = 0,
                            City = "Assiut",
                            ConcurrencyStamp = "1e697bee-130e-45c9-8f95-ace54dc6c462",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3731),
                            Email = "volunteer@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NationalID = "98765432109876",
                            NormalizedEmail = "VOLUNTEER@EXAMPLE.COM",
                            NormalizedUserName = "VOLUNTEER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6fBKgYj6nRAiD3F6jHUWfXeCmgVi+e3kq9a+vZ7O9GsG2vEMiRKzLskroIfvHHng==",
                            PhoneNumber = "01111111111",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "76123d09-48e8-4656-bd51-bc255dbd3d4d",
                            TwoFactorEnabled = false,
                            UserName = "volunteer@example.com"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Attendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("HoursWorked")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ParticipationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParticipationID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3824),
                            Description = "Educational programs and initiatives",
                            Icon = "education.png",
                            IsDeleted = false,
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParticipationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParticipationID")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasPreviousExperience")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.MailSetting.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwordResetTokens");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommercialRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("OrganizationProfiles");

                    b.HasData(
                        new
                        {
                            Id = "org-profile-1",
                            CommercialRegistration = "REG123456",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3700),
                            IsDeleted = false,
                            IsVerified = true,
                            OrganizationName = "Seeded Org",
                            UserID = "org-user-1"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("TotalAttendedHours")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLinkedToOpportunity")
                        .HasColumnType("bit");

                    b.Property<int?>("JoinPermission")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = "team-1",
                            CategoryId = "cat-edu-1",
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3857),
                            CreationDate = new DateTime(2025, 6, 12, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3849),
                            Description = "Team responsible for organizing educational initiatives.",
                            InternalNotes = "Priority team for large campaigns",
                            IsDeleted = false,
                            IsLinkedToOpportunity = true,
                            JoinPermission = 0,
                            MaxMembers = 20,
                            Name = "Education Support Team",
                            OrganizationID = "org-profile-1",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.TeamMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeamID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = "member-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3889),
                            IsDeleted = false,
                            JoinDate = new DateTime(2025, 6, 22, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3888),
                            Role = "Leader",
                            TeamID = "team-1",
                            VolunteerID = "vol-user-1"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerAchievement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AchievementID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<string>("VolunteerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VolunteerID");

                    b.ToTable("VolunteerAchievements");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerInvitation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("InvitationType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OpportunityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonalMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VolunteerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerInvitations");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenderRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAttendanceTracked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCertificateAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("TeamId");

                    b.ToTable("VolunteerOpportunities");

                    b.HasData(
                        new
                        {
                            Id = "opp-1",
                            CategoryID = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3922),
                            Description = "Help young children learn basic English skills.",
                            EndDate = new DateTime(2025, 8, 6, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3919),
                            Image = "english-teaching.png",
                            IsDeleted = false,
                            Location = "Cairo",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 10,
                            StartDate = new DateTime(2025, 7, 7, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3917),
                            Status = 1,
                            Title = "Teaching Kids English"
                        },
                        new
                        {
                            Id = "opp-2",
                            CategoryID = "cat-edu-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3926),
                            Description = "Lead a reading club for teenagers.",
                            EndDate = new DateTime(2025, 7, 22, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3925),
                            Image = "reading-club.png",
                            IsDeleted = false,
                            Location = "Assiut",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 5,
                            StartDate = new DateTime(2025, 7, 2, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3924),
                            Status = 1,
                            Title = "Reading Club Facilitator"
                        },
                        new
                        {
                            Id = "opp-3",
                            CategoryID = "cat-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3930),
                            Description = "Teach basic coding to children in underserved communities.",
                            EndDate = new DateTime(2025, 7, 17, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3929),
                            Image = "coding-kids.png",
                            IsDeleted = false,
                            Location = "Jeddah",
                            OrganizationID = "org-user-1",
                            RequiredVolunteers = 15,
                            StartDate = new DateTime(2025, 7, 7, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3928),
                            Status = 1,
                            TeamId = "team-1",
                            Title = "Coding for Kids"
                        });
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("VolunteerProfiles");

                    b.HasData(
                        new
                        {
                            Id = "vol-user-1",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3776),
                            Interests = "[\"Education\",\"Health\"]",
                            IsDeleted = false,
                            IsVerified = false,
                            Rating = 0f,
                            TotalHours = 0f,
                            UserID = "vol-user-1"
                        },
                        new
                        {
                            Id = "vol_prof2",
                            CreatedAt = new DateTime(2025, 6, 27, 11, 41, 4, 188, DateTimeKind.Utc).AddTicks(3802),
                            Interests = "[\"Education\",\"Health\"]",
                            IsDeleted = false,
                            IsVerified = false,
                            Rating = 0f,
                            TotalHours = 0f,
                            UserID = "1b5b5731-bcf1-4178-87ad-cf43dac0bbeb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Participation", "Participation")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Participation", "Participation")
                        .WithOne("Certificate")
                        .HasForeignKey("Tatawwa3.Domain.Entities.Certificate", "ParticipationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.MailSetting.PasswordResetToken", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithOne("OrganizationProfile")
                        .HasForeignKey("Tatawwa3.Domain.Entities.OrganizationProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Application", "Application")
                        .WithOne("Participation")
                        .HasForeignKey("Tatawwa3.Domain.Entities.Participation", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Application");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Skills", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.OrganizationProfile", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerAchievement", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerInvitation", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerOpportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId");

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Tatawwa3.Domain.Entities.VolunteerProfile", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.Category", "Category")
                        .WithMany("Opportunities")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.OrganizationProfile", "Organization")
                        .WithMany("VolunteerOpportunities")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tatawwa3.Domain.Entities.Team", "Team")
                        .WithMany("Opportunities")
                        .HasForeignKey("TeamId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerProfile", b =>
                {
                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Tatawwa3.Domain.Entities.ApplicationUser", "User")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("Tatawwa3.Domain.Entities.VolunteerProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Application", b =>
                {
                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("OrganizationProfile");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Category", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.OrganizationProfile", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("VolunteerOpportunities");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Participation", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Tatawwa3.Domain.Entities.VolunteerOpportunity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
